version: "3.9"

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "3040:3000"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=reservas1
      - POSTGRES_DB=reservas
      