version: "3.9"

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT:3000
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
