version: "3.9"

services:
  server:
    build: .
    ports:
      - "3000:3000"
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=reservas
      - POSTGRES_PASSWORD=reservas123
      - POSTGRES_USER=postgres